
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: <GATEWAY-NAME>
spec:
  gatewayClassName: <GATEWAY-NAME>
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
    - name: llm-gw
      protocol: HTTP
      port: 8081
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: <GATEWAY-NAME>
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend-dummy
spec:
  endpoints:
    - fqdn:
        # Both these values are arbitrary and unused as the PatchPolicy redirects requests.
        hostname: 'foo.bar.com'
        port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm-route
spec:
  parentRefs:
    - name: instance-gateway
      sectionName: llm-gw
  rules:
  - backendRefs:
      - group: gateway.envoyproxy.io
        kind: Backend
        name: backend-dummy
    timeouts:
      request: "24h"
      backendRequest: "24h"
