apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: envoy-gateway-system
data:
# This manifest's main purpose is to set `enabledEnvoyPatchPolicy` to `true`.
# Any field under `admin` is optional, and only for enabling the admin endpoints, for debugging.
# Admin Interface: https://www.envoyproxy.io/docs/envoy/latest/operations/admin
# PatchPolicy docs: https://gateway.envoyproxy.io/docs/tasks/extensibility/envoy-patch-policy/#enable-envoypatchpolicy 
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    provider:
      type: Kubernetes
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    extensionApis:
      enableEnvoyPatchPolicy: true
    admin:
      enablePprof: true
      address:
        host: 127.0.0.1
        port: 19000
      enabledDumpConfig: true
