# permissions for end users to edit llmserverpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/managed-by: kustomize
  name: llmserverpool-editor-role
rules:
- apiGroups:
  - gateway.inference.k8s.io
  resources:
  - llmserverpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.inference.k8s.io
  resources:
  - llmserverpools/status
  verbs:
  - get
